version: '3'

services:
  notary-db:
    container_name: notary-db
    build:
      context: database
      dockerfile: Dockerfile
    networks:
      - database
    volumes:
      - ./tmp/db/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
networks:
  database:
    driver: "bridge"
