OrdererOrgs:
  - Name: Orderer
    Domain: network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1